### ISSUE TITLE
Fuzzing detected problem

### ISSUE THREAD

**Issue by fzipi** [libinjection/libinjection#56]
Don't want this to be lost in pipelines, so:
```
NFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2784962097
INFO: Loaded 1 modules   (1 inline 8-bit counters): 1 [0x563f767f7160, 0x563f767f7161), 
INFO: Loaded 1 PC tables (1 PCs): 1 [0x563f767f7168,0x563f767f7178), 
INFO:      480 files found in ./src/fuzz/corpus
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 5891 bytes
INFO: seed corpus: files: 480 min: 2b max: 5891b total: 13390b rss: 35Mb
#481	INITED cov: 1 ft: 1 corp: 1/2b exec/s: 0 rss: 42Mb
#509	REDUCE cov: 1 ft: 1 corp: 1/1b lim: 6 exec/s: 0 rss: 42Mb L: 1/1 MS: 3 ChangeBinInt-CopyPart-EraseBytes-
#524288	pulse  cov: 1 ft: 1 corp: 1/1b lim: 5212 exec/s: 262144 rss: 81Mb
#1048576	pulse  cov: 1 ft: 1 corp: 1/1b lim: 5891 exec/s: 209715 rss: 121Mb
#2097152	pulse  cov: 1 ft: 1 corp: 1/1b lim: 5891 exec/s: 190650 rss: 199Mb
#4194304	pulse  cov: 1 ft: 1 corp: 1/1b lim: 5891 exec/s: 190650 rss: 355Mb
#8388608	pulse  cov: 1 ft: 1 corp: 1/1b lim: 5891 exec/s: 190650 rss: 620Mb
=================================================================
==6401==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602003ad9675 at pc 0x563f766472a2 bp 0x7ffe5d2b6320 sp 0x7ffe5d2b6318
READ of size 1 at 0x602003ad9675 thread T0
    #0 0x563f766472a1 in cstrcasecmp_with_null /home/runner/work/libinjection/libinjection/src/libinjection_xss.c:530:14
    #1 0x563f76646b07 in is_black_attr /home/runner/work/libinjection/libinjection/src/libinjection_xss.c:660:21
    #2 0x563f766445ce in libinjection_is_xss /home/runner/work/libinjection/libinjection/src/libinjection_xss.c:749:20
    #3 0x563f766474d5 in libinjection_xss /home/runner/work/libinjection/libinjection/src/libinjection_xss.c:841:9
    #4 0x563f76612e87 in LLVMFuzzerTestOneInput /home/runner/work/libinjection/libinjection/src/fuzz/fuzzer.c:14:3
    #5 0x563f76539333 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1ba333) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #6 0x563f76538a89 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1b9a89) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #7 0x563f7653a279 in fuzzer::Fuzzer::MutateAndTestOne() (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1bb279) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #8 0x563f7653adf5 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1bbdf5) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #9 0x563f76528f32 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1a9f32) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #10 0x563f76552c22 in main (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1d3c22) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #11 0x7fb0be029d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 962015aa9d133c6cbcfb31ec300596d7f44d3348)
    #12 0x7fb0be029e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 962015aa9d133c6cbcfb31ec300596d7f44d3348)
    #13 0x563f7651d974 in _start (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x19e974) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)

0x602003ad9675 is located 0 bytes to the right of 5-byte region [0x602003ad9670,0x602003ad9675)
allocated by thread T0 here:
    #0 0x563f7661086d in operator new[](unsigned long) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x29186d) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #1 0x563f76539242 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1ba242) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #2 0x563f76538a89 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1b9a89) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #3 0x563f7653a279 in fuzzer::Fuzzer::MutateAndTestOne() (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1bb279) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #4 0x563f7653adf5 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1bbdf5) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #5 0x563f76528f32 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1a9f32) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #6 0x563f76552c22 in main (/home/runner/work/libinjection/libinjection/src/fuzz/fuzzer+0x1d3c22) (BuildId: f0049fbab043b426b08e430830c369b373ae9ecb)
    #7 0x7fb0be029d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 962015aa9d133c6cbcfb31ec300596d7f44d3348)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/runner/work/libinjection/libinjection/src/libinjection_xss.c:530:14 in cstrcasecmp_with_null
Shadow bytes around the buggy address:
  0x0c0480753270: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480753280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480753290: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c04807532a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c04807532b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c04807532c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa[05]fa
  0x0c04807532d0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c04807532e0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c04807532f0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c0480753300: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c0480753310: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==6401==ABORTING
MS: 5 ShuffleBytes-InsertByte-CMP-ChangeBit-ShuffleBytes- DE: "sos"-; base unit: d1854cae891ec7b29161ccaf79a24b00c274bdaa
0x6f,0x6e,0x73,0x55,0x73,
onsUs
artifact_prefix='./'; Test unit written to ./crash-fbe1fd5373127fda76cae034380db17ae18a60df
Base64: b25zVXM=
Error: Process completed with exit code 1.
```

**Comment by fzipi** [comment]
I'm able to reproduce this one locally. Coudl this be a problem with the GH runners?

**Comment by airween** [comment]
Haven't we already fixed this via #64?

**Comment by airween** [comment]
> Maybe? Can you try to reproduce now?

I'm just asking because this issue was created on 2024-06-03, and #64 was opened and merged on 2025-02-28. And all [checks](https://github.com/libinjection/libinjection/pull/64/checks) were success.

I assume your next PR (#65) contains that fix and the tests were success too.

(I don't have anything to add now so I can't reproduce it in GH actions)

**Comment by fzipi** [comment]
Let's close then.
